#!/bin/bash -e

# Be sure to have LF as EOL
# and to chmod a+x

LOG=xt_arm.log

echo Results for FPC/ARM \(Raspberry Pi 3/B\) > $LOG
uname -a                                     >> $LOG
echo -e -n FPC version \\x20  >> $LOG
fpc -iW                       >> $LOG
echo ======================================  >> $LOG

SRC=t_xt_ws
fpc $SRC
echo >> $LOG
echo Result of $SRC >> $LOG
echo -------------------------------------- >> $LOG
./$SRC  test >> $LOG

SRC=t_xtmode
fpc $SRC
echo >> $LOG
echo Result of $SRC >> $LOG
echo -------------------------------------- >> $LOG
./$SRC >> $LOG

SRC=t_xt_csk
fpc $SRC
echo >> $LOG
echo Result of $SRC >> $LOG
echo -------------------------------------- >> $LOG
./$SRC >> $LOG

SRC=t_xt_xl
fpc $SRC
echo >> $LOG
echo Result of $SRC >> $LOG
echo -------------------------------------- >> $LOG
./$SRC >> $LOG

SRC=t_xtbas2
fpc $SRC
echo >> $LOG
echo Result of $SRC >> $LOG
echo -------------------------------------- >> $LOG
./$SRC >> $LOG
